"""Brain module - Claude API integration for intelligent agent behavior.

Uses Claude to:
  1. Generate tailored proposals that understand the job deeply
  2. Generate custom Solidity code for each specific job
  3. Respond to client messages and revision requests
  4. Analyze job requirements intelligently

Falls back to template-based responses if no API key is configured.
"""

import logging
from typing import Optional

logger = logging.getLogger("brain")

# Try to import anthropic - graceful fallback if not installed
try:
    import anthropic

    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False
    logger.info("anthropic package not installed - using template mode")

from config import ANTHROPIC_API_KEY

_client = None


def _get_client() -> Optional["anthropic.Anthropic"]:
    """Lazy-initialize the Anthropic client."""
    global _client
    if not HAS_ANTHROPIC or not ANTHROPIC_API_KEY:
        return None
    if _client is None:
        _client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    return _client


def is_ai_enabled() -> bool:
    """Check if AI features are available."""
    return HAS_ANTHROPIC and bool(ANTHROPIC_API_KEY)


SYSTEM_PROMPT = """You are defi_builder, an autonomous DeFi agent on the NEAR Agent Market.
You are a specialist in:
- Solidity smart contracts (0.8.26+, OpenZeppelin)
- Uniswap V4 Hooks (custom swap hooks, points systems, referral rewards)
- DeFi protocols (staking, lending, AMMs, vaults)
- Security audits (reentrancy, access control, flash loan attacks, MEV)
- Full-stack Web3 (Next.js, TypeScript, wagmi, RainbowKit)
- Foundry testing framework

You have REAL deployed code: a Uniswap V4 PointsHook on ETH Sepolia with a Next.js frontend.

Style: Technical, confident, concise. No fluff. Show expertise through specifics, not buzzwords."""


def generate_smart_proposal(job: dict) -> Optional[str]:
    """Use Claude to generate a tailored proposal for a specific job."""
    client = _get_client()
    if not client:
        return None

    title = job.get("title", "")
    desc = job.get("description", "")[:2000]
    budget = job.get("budget_amount", "?")
    tags = ", ".join(job.get("tags", []))

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=400,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": f"""Write a bid proposal for this job on the NEAR Agent Market.

Job Title: {title}
Description: {desc}
Budget: {budget} NEAR
Tags: {tags}

Rules:
- MAX 3-4 sentences. Be specific to THIS job, not generic.
- Reference your real experience (deployed Uniswap V4 hooks, Foundry tests, Next.js frontends)
- Mention a specific technical approach you'll take for THIS job
- End with estimated delivery time
- NO markdown, NO bullet points. Just a clean paragraph.
- Sound like a senior dev, not a salesman.""",
                }
            ],
        )
        proposal = response.content[0].text.strip()
        logger.info("AI proposal generated (%d chars)", len(proposal))
        return proposal
    except Exception as e:
        logger.warning("AI proposal failed: %s", e)
        return None


def generate_smart_code(job: dict) -> Optional[str]:
    """Use Claude to generate tailored Solidity code for a specific job."""
    client = _get_client()
    if not client:
        return None

    title = job.get("title", "")
    desc = job.get("description", "")[:3000]
    tags = ", ".join(job.get("tags", []))

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=4000,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": f"""Generate a complete Solidity deliverable for this job.

Job Title: {title}
Description: {desc}
Tags: {tags}

Requirements:
- If the job asks for Solidity code: write a complete, compilable contract (Solidity 0.8.26, OpenZeppelin imports)
- If the job asks for an audit: write a structured security audit report with findings
- If the job asks for documentation: write technical docs
- If the job asks for something else: write the most useful deliverable you can

Include:
- Proper SPDX license and pragma
- NatSpec comments
- Events for key state changes
- A commented Foundry test outline at the bottom
- "Generated by defi_builder agent" in a comment

Write ONLY the deliverable content. No explanations before or after.""",
                }
            ],
        )
        code = response.content[0].text.strip()
        logger.info("AI code generated (%d chars)", len(code))
        return code
    except Exception as e:
        logger.warning("AI code generation failed: %s", e)
        return None


def generate_revision_response(
    job: dict, client_message: str, original_deliverable: str
) -> Optional[str]:
    """Use Claude to respond to a client's revision request."""
    client = _get_client()
    if not client:
        return None

    title = job.get("title", "")

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=4000,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": f"""A client sent a message about a job you delivered.

Job: {title}
Original deliverable (first 1500 chars):
{original_deliverable[:1500]}

Client message: {client_message}

If they're asking for a revision, generate the UPDATED deliverable incorporating their feedback.
If they're asking a question, answer it concisely.
If they're saying thanks, respond briefly and professionally.

Respond with ONLY the message/deliverable content.""",
                }
            ],
        )
        reply = response.content[0].text.strip()
        logger.info("AI revision response generated (%d chars)", len(reply))
        return reply
    except Exception as e:
        logger.warning("AI revision response failed: %s", e)
        return None


def analyze_job_fit(job: dict) -> Optional[dict]:
    """Use Claude to deeply analyze if a job is a good fit and why."""
    client = _get_client()
    if not client:
        return None

    title = job.get("title", "")
    desc = job.get("description", "")[:1500]
    tags = ", ".join(job.get("tags", []))
    budget = job.get("budget_amount", "?")

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": f"""Analyze this job for defi_builder agent (DeFi/Solidity specialist).

Title: {title}
Description: {desc}
Tags: {tags}
Budget: {budget} NEAR

Reply in EXACTLY this format (no other text):
SCORE: 0.XX
REASON: one sentence why
APPROACH: one sentence how you'd tackle it""",
                }
            ],
        )
        text = response.content[0].text.strip()

        # Parse the structured response
        result = {}
        for line in text.split("\n"):
            if line.startswith("SCORE:"):
                try:
                    result["score"] = float(line.split(":")[1].strip())
                except ValueError:
                    result["score"] = 0.5
            elif line.startswith("REASON:"):
                result["reason"] = line.split(":", 1)[1].strip()
            elif line.startswith("APPROACH:"):
                result["approach"] = line.split(":", 1)[1].strip()

        return result if "score" in result else None
    except Exception as e:
        logger.warning("AI job analysis failed: %s", e)
        return None
