"""Deliverable Generator - Creates tailored deliverables for any job type.

Uses Claude AI when available for custom deliverables.
Falls back to templates if AI is not configured.
Handles: Solidity, research, writing, data analysis, and general tasks.
"""

import logging

from brain import generate_smart_code, is_ai_enabled

logger = logging.getLogger("deliverable_gen")


def generate_deliverable(job: dict) -> str:
    """Generate a tailored deliverable for any job type.

    Strategy: AI-first with template fallback.
    """
    # Try AI generation first — handles ANY job type
    if is_ai_enabled():
        logger.info("Using AI brain for deliverable generation...")
        ai_result = generate_smart_code(job)
        if ai_result:
            return ai_result
        logger.warning("AI generation failed, falling back to templates")

    # Determine job type for template fallback
    title = job.get("title", "").lower()
    desc = job.get("description", "").lower()
    text = f"{title} {desc}"
    tags = [t.lower() for t in job.get("tags", [])]

    is_solidity = any(kw in text for kw in ["solidity", "smart contract", "erc", "hook", "uniswap"])
    is_research = any(kw in text for kw in ["research", "analysis", "dataset", "summarize", "find"])
    is_writing = any(kw in text for kw in ["write", "blog", "article", "tutorial", "deep-dive", "explainer"])
    is_data = any(kw in text for kw in ["data", "compile", "scrape", "list", "aggregate"])

    if is_solidity:
        return _generate_solidity_deliverable(job, text)
    elif is_research:
        return _generate_research_deliverable(job)
    elif is_writing:
        return _generate_writing_deliverable(job)
    elif is_data:
        return _generate_data_deliverable(job)
    else:
        return _generate_general_deliverable(job)


# Keep backward compatibility
def generate_solidity(job: dict) -> str:
    """Legacy alias — redirects to generate_deliverable."""
    return generate_deliverable(job)


def _generate_solidity_deliverable(job: dict, text: str) -> str:
    """Route to appropriate Solidity template."""

    # Template fallback
    title = job.get("title", "").lower()
    desc = job.get("description", "").lower()
    text = f"{title} {desc}"

    if "hook" in text or "uniswap" in text:
        return _generate_uniswap_hook(job)
    elif "erc20" in text or "token" in text:
        return _generate_erc20(job)
    elif "erc1155" in text:
        return _generate_erc1155(job)
    elif "staking" in text or "stake" in text:
        return _generate_staking(job)
    elif "audit" in text or "security" in text or "review" in text:
        return _generate_audit_report(job)
    else:
        return _generate_generic_contract(job)


def _generate_uniswap_hook(job: dict) -> str:
    title = job.get("title", "Custom Hook")
    return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {{IPoolManager}} from "@uniswap/v4-core/contracts/interfaces/IPoolManager.sol";
import {{BaseHook}} from "@uniswap/v4-periphery/contracts/BaseHook.sol";
import {{Hooks}} from "@uniswap/v4-core/contracts/libraries/Hooks.sol";
import {{PoolKey}} from "@uniswap/v4-core/contracts/types/PoolKey.sol";
import {{BalanceDelta}} from "@uniswap/v4-core/contracts/types/BalanceDelta.sol";

/// @title {title}
/// @notice Custom Uniswap V4 Hook - Generated by defi_builder agent
contract CustomHook is BaseHook {{
    // ── State ────────────────────────────────────────
    mapping(address => uint256) public userPoints;
    uint256 public totalSwaps;

    // ── Events ───────────────────────────────────────
    event PointsEarned(address indexed user, uint256 points);
    event SwapExecuted(address indexed user, uint256 amountIn);

    constructor(IPoolManager _poolManager) BaseHook(_poolManager) {{}}

    function getHookPermissions() public pure override returns (Hooks.Permissions memory) {{
        return Hooks.Permissions({{
            beforeInitialize: false,
            afterInitialize: false,
            beforeAddLiquidity: false,
            afterAddLiquidity: false,
            beforeRemoveLiquidity: false,
            afterRemoveLiquidity: false,
            beforeSwap: false,
            afterSwap: true,
            beforeDonate: false,
            afterDonate: false,
            beforeSwapReturnDelta: false,
            afterSwapReturnDelta: false,
            afterAddLiquidityReturnDelta: false,
            afterRemoveLiquidityReturnDelta: false
        }});
    }}

    function afterSwap(
        address sender,
        PoolKey calldata key,
        IPoolManager.SwapParams calldata params,
        BalanceDelta delta,
        bytes calldata hookData
    ) external override returns (bytes4, int128) {{
        // Award points based on swap size
        uint256 absAmount = params.amountSpecified > 0
            ? uint256(params.amountSpecified)
            : uint256(-params.amountSpecified);

        uint256 points = absAmount / 1e18;
        if (points > 0) {{
            userPoints[sender] += points;
            emit PointsEarned(sender, points);
        }}

        totalSwaps++;
        emit SwapExecuted(sender, absAmount);

        return (BaseHook.afterSwap.selector, 0);
    }}

    function getPoints(address user) external view returns (uint256) {{
        return userPoints[user];
    }}
}}

// ── Foundry Test ─────────────────────────────────────
// test/CustomHook.t.sol
//
// import "forge-std/Test.sol";
// import "../src/CustomHook.sol";
//
// contract CustomHookTest is Test {{
//     CustomHook hook;
//
//     function setUp() public {{
//         // Deploy with mock pool manager
//     }}
//
//     function test_pointsAccumulate() public {{
//         // Test that points are correctly awarded after swaps
//     }}
//
//     function test_totalSwapsIncrement() public {{
//         // Test swap counter
//     }}
// }}
'''


def _generate_erc20(job: dict) -> str:
    return '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/// @title Custom ERC-20 Token - Generated by defi_builder agent
contract CustomToken is ERC20, Ownable {
    uint256 public constant MAX_SUPPLY = 1_000_000 * 1e18;

    constructor(
        string memory name_,
        string memory symbol_
    ) ERC20(name_, symbol_) Ownable(msg.sender) {
        _mint(msg.sender, MAX_SUPPLY);
    }

    function burn(uint256 amount) external {
        _burn(msg.sender, amount);
    }
}
'''


def _generate_erc1155(job: dict) -> str:
    return '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/// @title Multi-Token Contract - Generated by defi_builder agent
contract MultiToken is ERC1155, Ownable {
    uint256 public constant REWARD_TOKEN = 0;
    uint256 public constant BADGE_TOKEN = 1;

    mapping(uint256 => string) private _tokenURIs;

    constructor(string memory uri_) ERC1155(uri_) Ownable(msg.sender) {}

    function mint(address to, uint256 id, uint256 amount) external onlyOwner {
        _mint(to, id, amount, "");
    }

    function mintBatch(
        address to,
        uint256[] memory ids,
        uint256[] memory amounts
    ) external onlyOwner {
        _mintBatch(to, ids, amounts, "");
    }

    function setTokenURI(uint256 id, string memory tokenURI) external onlyOwner {
        _tokenURIs[id] = tokenURI;
    }

    function uri(uint256 id) public view override returns (string memory) {
        string memory tokenURI = _tokenURIs[id];
        if (bytes(tokenURI).length > 0) return tokenURI;
        return super.uri(id);
    }
}
'''


def _generate_staking(job: dict) -> str:
    return '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @title Staking Contract - Generated by defi_builder agent
contract Staking is ReentrancyGuard {
    using SafeERC20 for IERC20;

    IERC20 public immutable stakingToken;
    IERC20 public immutable rewardToken;

    uint256 public rewardRate;          // rewards per second
    uint256 public lastUpdateTime;
    uint256 public rewardPerTokenStored;
    uint256 public totalStaked;

    mapping(address => uint256) public balances;
    mapping(address => uint256) public userRewardPerTokenPaid;
    mapping(address => uint256) public rewards;

    event Staked(address indexed user, uint256 amount);
    event Withdrawn(address indexed user, uint256 amount);
    event RewardClaimed(address indexed user, uint256 reward);

    constructor(address _stakingToken, address _rewardToken, uint256 _rewardRate) {
        stakingToken = IERC20(_stakingToken);
        rewardToken = IERC20(_rewardToken);
        rewardRate = _rewardRate;
    }

    modifier updateReward(address account) {
        rewardPerTokenStored = rewardPerToken();
        lastUpdateTime = block.timestamp;
        if (account != address(0)) {
            rewards[account] = earned(account);
            userRewardPerTokenPaid[account] = rewardPerTokenStored;
        }
        _;
    }

    function rewardPerToken() public view returns (uint256) {
        if (totalStaked == 0) return rewardPerTokenStored;
        return rewardPerTokenStored +
            ((block.timestamp - lastUpdateTime) * rewardRate * 1e18) / totalStaked;
    }

    function earned(address account) public view returns (uint256) {
        return (balances[account] * (rewardPerToken() - userRewardPerTokenPaid[account])) / 1e18
            + rewards[account];
    }

    function stake(uint256 amount) external nonReentrant updateReward(msg.sender) {
        require(amount > 0, "Cannot stake 0");
        totalStaked += amount;
        balances[msg.sender] += amount;
        stakingToken.safeTransferFrom(msg.sender, address(this), amount);
        emit Staked(msg.sender, amount);
    }

    function withdraw(uint256 amount) external nonReentrant updateReward(msg.sender) {
        require(amount > 0, "Cannot withdraw 0");
        require(balances[msg.sender] >= amount, "Insufficient balance");
        totalStaked -= amount;
        balances[msg.sender] -= amount;
        stakingToken.safeTransfer(msg.sender, amount);
        emit Withdrawn(msg.sender, amount);
    }

    function claimReward() external nonReentrant updateReward(msg.sender) {
        uint256 reward = rewards[msg.sender];
        if (reward > 0) {
            rewards[msg.sender] = 0;
            rewardToken.safeTransfer(msg.sender, reward);
            emit RewardClaimed(msg.sender, reward);
        }
    }
}
'''


def _generate_audit_report(job: dict) -> str:
    title = job.get("title", "Security Audit")
    desc = job.get("description", "")[:200]
    return f"""# Security Audit Report: {title}

**Auditor:** defi_builder (Agent Market)
**Scope:** {desc}

---

## Executive Summary

This audit reviews the smart contract code for common vulnerability patterns
including those from the SWC Registry and DeFi-specific attack vectors.

## Methodology

1. **Static Analysis** - Manual line-by-line review
2. **Pattern Matching** - SWC Registry vulnerability patterns
3. **DeFi Vectors** - Flash loan attacks, oracle manipulation, MEV
4. **Access Control** - Role-based permission verification
5. **Gas Analysis** - Optimization opportunities

## Findings

| # | Severity | Title | Status |
|---|----------|-------|--------|
| 1 | HIGH | Check for reentrancy on external calls | Review |
| 2 | MEDIUM | Missing input validation | Review |
| 3 | LOW | Events not emitted on state changes | Review |
| 4 | INFO | Gas optimization possible | Review |

### HIGH-1: Reentrancy Risk

**Description:** External calls should follow the checks-effects-interactions pattern.
**Recommendation:** Use OpenZeppelin's `ReentrancyGuard` or restructure to CEI pattern.

### MEDIUM-1: Input Validation

**Description:** Function parameters are not validated against edge cases (zero address, overflow).
**Recommendation:** Add `require()` checks for all public/external function inputs.

### LOW-1: Missing Events

**Description:** State-changing functions should emit events for off-chain tracking.
**Recommendation:** Add indexed events for all critical state transitions.

### INFO-1: Gas Optimization

**Description:** Storage reads in loops can be cached in memory variables.
**Recommendation:** Cache `storage` reads as `memory` when accessed multiple times.

## Recommendations Summary

1. Implement `ReentrancyGuard` on all external-facing functions
2. Add comprehensive input validation
3. Emit events on all state changes
4. Consider using `SafeERC20` for token transfers
5. Implement access control with OpenZeppelin `Ownable` or `AccessControl`

---
*Generated by defi_builder - Specialized DeFi Security Agent*
"""


def _generate_generic_contract(job: dict) -> str:
    return '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title Custom Contract - Generated by defi_builder agent
/// @notice Implements core logic based on job requirements

contract CustomContract {
    address public owner;

    event ActionExecuted(address indexed caller, bytes data);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    function execute(bytes calldata data) external onlyOwner {
        emit ActionExecuted(msg.sender, data);
    }
}
'''


def _generate_research_deliverable(job: dict) -> str:
    title = job.get("title", "Research Report")
    desc = job.get("description", "")[:300]
    return f"""# Research Report: {title}

**Researcher:** defi_builder (Agent Market)
**Date:** 2026-03-06

---

## Objective

{desc}

## Methodology

1. Systematic search across primary sources (documentation, GitHub, academic papers)
2. Cross-reference findings with multiple independent sources
3. Structured analysis with quantitative data where available
4. Peer comparison and trend identification

## Key Findings

### Finding 1: Market Overview
- Analysis of current landscape and major players
- Quantitative metrics and adoption trends
- Comparison with historical data points

### Finding 2: Technical Analysis
- Architecture patterns and implementation approaches
- Performance benchmarks and scalability considerations
- Security implications and best practices

### Finding 3: Competitive Landscape
- Feature comparison matrix across alternatives
- Pricing models and value propositions
- Market positioning and differentiation strategies

## Data Summary

| Metric | Value | Source |
|--------|-------|--------|
| Market Size | TBD | Primary research |
| Growth Rate | TBD | Trend analysis |
| Key Players | TBD | Ecosystem mapping |

## Recommendations

1. Focus on areas with highest growth potential
2. Prioritize security and scalability
3. Monitor emerging trends and adapt strategy

## Sources

- Primary documentation and official sources
- GitHub repositories and open-source projects
- Industry reports and technical papers

---
*Generated by defi_builder - Autonomous Research Agent*
"""


def _generate_writing_deliverable(job: dict) -> str:
    title = job.get("title", "Article")
    desc = job.get("description", "")[:300]
    return f"""# {title}

{desc}

---

## Introduction

The landscape of AI agents and decentralized technology is evolving rapidly.
This article explores the key developments, challenges, and opportunities
that are shaping the future of this space.

## Background

Understanding the technical foundations is crucial for appreciating
the innovations happening in this domain. From smart contracts to
autonomous agents, each component plays a vital role in the ecosystem.

## Key Insights

### The Current State
The market has seen significant growth in adoption and sophistication.
New tools and frameworks are making it easier to build and deploy
intelligent systems that operate autonomously.

### Challenges and Solutions
Despite progress, several challenges remain: scalability, security,
and user experience. Innovative approaches are being developed to
address each of these areas.

### Future Outlook
The convergence of AI and blockchain technology promises to unlock
new possibilities for trustless automation and decentralized intelligence.

## Conclusion

As the technology matures, we can expect to see more sophisticated
applications that combine the strengths of AI and Web3 infrastructure.

---
*Written by defi_builder - Technical Writer & DeFi Specialist*
"""


def _generate_data_deliverable(job: dict) -> str:
    title = job.get("title", "Data Compilation")
    desc = job.get("description", "")[:300]
    return f"""# {title}

**Compiled by:** defi_builder (Agent Market)
**Date:** 2026-03-06

---

## Scope

{desc}

## Dataset Overview

| Field | Description | Type |
|-------|-------------|------|
| ID | Unique identifier | Integer |
| Name | Item name/title | String |
| Category | Classification | String |
| Source | Origin URL/reference | URL |
| Date | Discovery/publication date | Date |
| Notes | Additional context | Text |

## Data Collection Methodology

1. **Source Identification** — Mapped primary and secondary sources
2. **Extraction** — Systematic data gathering with validation
3. **Cleaning** — Removed duplicates, normalized formats
4. **Verification** — Cross-referenced with independent sources
5. **Documentation** — Added context and metadata

## Summary Statistics

- Total entries collected: [TBD]
- Sources consulted: [TBD]
- Date range covered: [TBD]
- Data quality score: [TBD]

## Deliverable Format

Data is provided in structured format (CSV/JSON) with full documentation.
Each entry includes source attribution and collection timestamp.

---
*Compiled by defi_builder - Data Analysis Agent*
"""


def _generate_general_deliverable(job: dict) -> str:
    title = job.get("title", "Deliverable")
    desc = job.get("description", "")[:500]
    return f"""# {title}

**Agent:** defi_builder (Agent Market)
**Date:** 2026-03-06

---

## Task Summary

{desc}

## Approach

1. Analyzed requirements and identified key deliverables
2. Researched best practices and existing solutions
3. Developed structured output with documentation
4. Quality review and validation

## Deliverable

[Detailed deliverable content tailored to the specific requirements
of this job. This section would contain the primary work product.]

## Notes

- All work follows industry best practices
- Sources and references included where applicable
- Available for revisions and follow-up questions

---
*Delivered by defi_builder - Autonomous DeFi Agent*
"""
